MyFirstWebApp/Models/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstWebApp.Models
{
    public class CategoryModel
    {
        
        public int Id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(20)]
        [Display(Name="Name: ")]
        public string Name { get; set; }
    }
}

MyFirstWebApp/Models/ErrorViewModel.cs
using System;

namespace MyFirstWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstWebApp/Models/ItemModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstWebApp.Models
{
    public class ItemModel
    {
        
        public int Id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(50)]
        [Display(Name = "Name: ")]
        public string Name { get; set; }
        [Required]
       
        [Display( Name= "Price, $: ")]
        public int Price { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(200)]
        [Display(Description = "Description: ")]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [StringLength(50)]
        [Display(Name = "Location: ")]

        public string Location { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(50)]
        [Display(Name = "Category: ")]

        public string CategoryName { get; set; }
        public CategoryModel Category { get; set; }
    }
}

MyFirstWebApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebApp.Database;
using MyFirstWebApp.Models;

namespace MyFirstWebApp.Controllers
{
    public class CategoryController : Controller
    {
        public static List<CategoryModel> Categories = new List<CategoryModel>();
           
        public IActionResult Index()
        {
            
            using (var db = new Database.DB())
            {
              var model = db.Categories.OrderBy(c => c.Name).
                    Select(c=> new CategoryModel()
                    {
                        Id = c.Id,
                        Name = c.Name,
                    })
                    .ToList();  
                return base.View(model);
            }
        }
       
        [HttpGet]
        public IActionResult Create()
        {
            var model = new CategoryModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(CategoryModel model)
        {
            if(ModelState.IsValid)
            {
                using (var db = new Database.DB())
                {
                    db.Categories.Add(new Database.Categories()
                    {
                        Name = model.Name,
                    });
                    db.SaveChanges();
                      
                }
                   
            return RedirectToAction(nameof(Index));
        }
            return View(model);
        }
    }
}

MyFirstWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebApp.Models;

namespace MyFirstWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstWebApp/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebApp.Database;
using MyFirstWebApp.Models;

namespace MyFirstWebApp.Controllers
{
    public class ItemController : Controller
    {


        public IActionResult Index(int? id)
        {

            using (var db = new DB())
            {
                var model = db.Items.OrderBy(i => i.Price)
                    .Select(i => new ItemModel()
                    {
                        Id = i.Id,
                        Description = i.Description,
                        Location = i.Location,
                        Name = i.Name,
                        Price = i.Price.Value,
                        Category = new CategoryModel()
                        {
                            Id = i.CategoryId,
                        }
                    })
                    .ToList();

                if (id.HasValue)
                {
                    model = model.Where(i => i.Category.Id == id).ToList();

                }

                return View(model);
            }
        }
        public IActionResult View(int id)
        {
            using (var db = new DB())
            {
                var item = db.Items.Find(id);
                var model = new ItemModel()
                {
                    Id = item.Id,
                    Description = item.Description,
                    Location = item.Location,
                    Name = item.Name,
                    Price = item.Price.Value,
                    Category = new CategoryModel()
                    {
                        Id = item.CategoryId,
                    }
                };
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new ItemModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(ItemModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new DB())
                {
                    var category = db.Categories.FirstOrDefault(c => c.Name == model.CategoryName);

                    if (category != null)
                    {
                        db.Items.Add(new Database.Items()
                        {

                            Description = model.Description,
                            Location = model.Location,
                            Name = model.Name,
                            Price = model.Price,
                            CategoryId = category.Id,
                        });
                        db.SaveChanges();

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("cat", "Category not found!");

                    }
                }

            }
            return View(model);
        }
    }
}

MyFirstWebApp/Views/Category/Create.cshtml
@model CategoryModel
@{
    ViewData["Title"] = "Add new category";
}

<h2>Add new category</h2>
@Html.ValidationSummary()
<form class="form-horizontal" asp-controller="Category" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input class="form-control" asp-for="Name">
            </div>
    </div>
    <div class="form-group">
        
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Save</button>
            </div>
    </div>
    </form>

MyFirstWebApp/Views/Category/Index.cshtml
@model List<CategoryModel>
@{
    ViewData["Title"] = "Categories";
}

<h2>Categories</h2>
<table class=" table table-striped">
    <tr>
       <th>#</th>
        <th>Name</th>
        <th></th>
    </tr>
    @foreach(var category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>@category.Name</td>
            <td><a asp-controller="Item" asp-action="Index" asp-route-id="@category.Id">View items</a></td>
        </tr>
        
    }
</table>

<footer><a href="#" onclick="history.back(); return false;">Atpakaļ</a></footer>

MyFirstWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyFirstWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyFirstWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>My Web Catalogue</h1>

MyFirstWebApp/Views/Item/Create.cshtml
@model ItemModel
@{
    ViewData["Title"] = "Add new item";
}

<h2>Add new item</h2>
@Html.ValidationSummary()
<form class="form-horizontal" asp-controller="Item" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Name">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Price" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Price">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Description">
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Location" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="Location">
        </div>
    </div>
    <div class="form-group">
        <label asp-for="CategoryName" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="CategoryName">
        </div>
    </div>
    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

MyFirstWebApp/Views/Item/Index.cshtml
@model List<ItemModel>
@{
    ViewData["Title"] = "Items";
}

<h2>Items</h2>
<br />
<a asp-controller="Category" asp-action="Index">Atpakaļ</a>
<br />
@if (Model.Count >0)
{ 

<table class=" table table-striped">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Price, €</th>
        <th>Description</th>
        <th></th>
    </tr>
   
    @foreach (var item in Model)

    {
<tr>
    <td>@item.Id</td>
    <td>@item.Name</td>
    <td>@item.Price</td>
    <td>@item.Description</td>
    <td><a asp-controller="Item" asp-action="View" asp-route-id="@item.Id">View</a></td>
</tr>

    }
</table>
    }
    else
    {
    <div>Šajā kategorijā nav preču!</div>
    }

MyFirstWebApp/Views/Item/View.cshtml
@model ItemModel
@{
    ViewData["Title"] = " View Item";
}

<h2>@Model.Name</h2>
<div>
    Name: @Model.Name
</div>
<div>
    Category: @Model.Category.Name
</div>
<div>
    Price: @Model.Price
</div>
<div>
    Description: @Model.Description
</div>
<div>
    Location: @Model.Location
</div>

<br />
<a asp-controller="Category" asp-action="Index">Atpakaļ</a>
<br />